<a href="https://colab.research.google.com/github/Danielahv07/7688581-Expert-Git-GitHub/blob/main/PARTIEL_VF_S2_IA_M1_Mod%C3%A9lisation_de_S%C3%A9rie_Temporelle_en_Python_docx_ANNEXE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Contrôle Time Series

### Consignes
- ChatGPT interdit
- Documentations autorisées

> statsmodel https://www.statsmodels.org/stable/index.html

> pandas https://pandas.pydata.org/docs/

> matplotlib https://matplotlib.org/stable/index.html

### Format de rendu
- Rendre ce fichier complété (notebook)

### Attentes
- Les questions doivent être répondues
- Le code doit être commenté

## Partie 1: Exploration des données

In [1]:
import pandas as pd
import statsmodels
import numpy as np
from statsmodels.datasets import macrodata
import matplotlib.pyplot as plt

In [2]:
# chargement du jeu de donnée
df = pd.DataFrame(macrodata.load_pandas().data)

In [3]:
df

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint
0,1959.0,1.0,2710.349,1707.4,286.898,470.045,1886.9,28.980,139.7,2.82,5.8,177.146,0.00,0.00
1,1959.0,2.0,2778.801,1733.7,310.859,481.301,1919.7,29.150,141.7,3.08,5.1,177.830,2.34,0.74
2,1959.0,3.0,2775.488,1751.8,289.226,491.260,1916.4,29.350,140.5,3.82,5.3,178.657,2.74,1.09
3,1959.0,4.0,2785.204,1753.7,299.356,484.052,1931.3,29.370,140.0,4.33,5.6,179.386,0.27,4.06
4,1960.0,1.0,2847.699,1770.5,331.722,462.199,1955.5,29.540,139.6,3.50,5.2,180.007,2.31,1.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,2008.0,3.0,13324.600,9267.7,1990.693,991.551,9838.3,216.889,1474.7,1.17,6.0,305.270,-3.16,4.33
199,2008.0,4.0,13141.920,9195.3,1857.661,1007.273,9920.4,212.174,1576.5,0.12,6.9,305.952,-8.79,8.91
200,2009.0,1.0,12925.410,9209.2,1558.494,996.287,9926.4,212.671,1592.8,0.22,8.1,306.547,0.94,-0.71
201,2009.0,2.0,12901.504,9189.0,1456.678,1023.528,10077.5,214.469,1653.6,0.18,9.2,307.226,3.37,-3.19
202,2009.0,3.0,12990.341,9256.0,1486.398,1044.088,10040.6,216.385,1673.9,0.12,9.6,308.013,3.56,-3.44

### Question 1

- Effectuer les transformations necessaires (type, index) pour transformer le dataframe en time-series

In [4]:
# votre code ici

In [5]:
# votre code ici

### Question 2

La colonne 'infl' du jeu de données "Macrodata" de statsmodels correspond au taux d'inflation aux États-Unis. Le jeu de données "Macrodata" contient des variables économiques et financières, et 'infl' représente spécifiquement le taux d'inflation.

Le taux d'inflation mesure la variation des prix des biens et services dans une économie au fil du temps. Il est souvent exprimé en pourcentage et est utilisé pour évaluer l'évolution du niveau général des prix. Une valeur positive du taux d'inflation indique une augmentation des prix, tandis qu'une valeur négative indique une baisse des prix.

- 2.1 Effectuer un regroupement par année, en calculant la moyenne sur l'année.

- 2.2 Calculer les moyennes mobiles glissante tous les 4 ans pour 'infl'

- 2.3 Calculer les moyennes mobiles exponentielles tous les 4 ans pour 'infl'

- 2.4 Effectuer un graphique comportant 'infl' original ainsi que la MM4 infl de la question 2.2 et la EXPMM4 de la question 2.3

- 2.5 Observer le graphique d'un point de vue temporel. Comment se comporte le taux d'inflation au US ? Effectuez des hypothèses sur les changement de tendances. Pour cela, vous pouvez vous appuyer sur ce lien : https://fr.wikipedia.org/wiki/%C3%89conomie_des_%C3%89tats-Unis

- 2.6 Comparer la moyenne mobile et la moyenne mobile exponentielle. Pourquoi retrouve t on des différence dans les courbes ?Que cela signifie ?

In [ ]:
# question 2.1

In [ ]:
# question 2.2

In [ ]:
# question 2.3

In [ ]:
# question 2.4

In [ ]:
# question 2.5

In [ ]:
# question 2.6

## Partie 2: Machine Learning

In [6]:
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.seasonal import seasonal_decompose
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv("https://s3.amazonaws.com/assets.datacamp.com/production/course_5226/datasets/ch4_meat.csv")

In [8]:
df

,date,beef,veal,pork,lamb_and_mutton,broilers,other_chicken,turkey
0,1944-01-01,751.0,85.0,1280.0,89.0,NaN,NaN,NaN
1,1944-02-01,713.0,77.0,1169.0,72.0,NaN,NaN,NaN
2,1944-03-01,741.0,90.0,1128.0,75.0,NaN,NaN,NaN
3,1944-04-01,650.0,89.0,978.0,66.0,NaN,NaN,NaN
4,1944-05-01,681.0,106.0,1029.0,78.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
822,2012-07-01,2200.8,9.5,1721.8,12.5,3127.0,43.4,497.2
823,2012-08-01,2367.5,10.1,1997.9,14.2,3317.4,51.0,530.1
824,2012-09-01,2016.0,8.8,1911.0,12.5,2927.1,43.7,453.1
825,2012-10-01,2343.7,10.3,2210.4,14.2,3335.0,43.8,579.9
826,2012-11-01,2206.6,10.1,2078.7,12.4,3006.7,37.5,515.3

### Question 3

Le jeu de donnée correspond à la consommation de produit de viande.

- 3.1 Après avoir indexé la time-series, effectuer un regroupement par année, en calculant la moyenne sur l'année.

- 3.2 Effectuer une decomposition saisonniere pour la variable 'beef'

- 3.3 Analyser chaque point de la decomposition: tendance, saisonnalité et bruit

- 3.4 Effectuer un test de stationnarité et trancher sur la stationnarité de la variable

- 3.5 Si necessaire, effectuer des transformations mathematique pour rendre la variable stationnaire

In [ ]:
# question 3.1

In [ ]:
# question 3.2

In [ ]:
# question 3.3

In [ ]:
# question 3.4

In [ ]:
# question 3.5

### Question 4

A partir de votre analyse précédente ou d'une nouvelle analyse, proposez un model de machine learning (celui de votre choix) et effectuer une prédiction pour la variable 'beef' jusqu'a l'année 2018 inclus.

Vous veillerez à:
- evaluer votre model
- commenter les résultats du model
- effectuer un graphique de prediction du model

In [ ]:
# question 4

In [ ]:
# question 4

In [ ]:
# question 4

In [ ]:
# question 4